x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

version: "3.7"
services:
  api:
    restart: always
    build: .
    ports:
      - "80:80"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 57213fb7aa2b771ca92e00d3aa6863fe

# .\gradlew build ; docker-compose up -d --build
