x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

version: "3.7"
services:
  api:
    restart: always
    build: api
    ports:
      - "80:80"
    environment:
      TOKEN_JWT: ${TOKEN_JWT}
      DB_USER_ROOT: ${DB_USER_ROOT}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - api-toggle
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - api-toggle
  nginx:
    restart: always
    build: nginx
    ports:
      - "443:443"
    networks:
      - api-toggle
networks:
  api-toggle:

volumes:
  api-toggle:

# compose up -d --no-build --remove-orphans
# .\gradlew build -x test